djangoProject/urls.py
from django.contrib import admin
from django.urls import path

from barek.views import CabinetListView, CreateCabinetView, CreateBottleView, CabinetDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cabinets/', CabinetListView.as_view(), name='cabinets'),
    path('cabinet/', CreateCabinetView.as_view(), name='add-cabinet'),
    path('cabinet/<int:pk>', CabinetDetailView.as_view(), name='cabinet-detail'),
    path('bottle/', CreateBottleView.as_view(), name='add-bottle'),

]

barek/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Cabinet(models.Model):
    location = models.TextField()

    def get_absolute_url(self):
        return reverse('cabinets')

    def __str__(self):
        return self.location


class Bottle(models.Model):
    cabinet = models.ForeignKey(Cabinet, on_delete=models.CASCADE)
    producer = models.TextField()
    production_year = models.DateField()
    volume = models.DecimalField(decimal_places=2, max_digits=4)

    def get_absolute_url(self):
        return reverse('cabinets')

    def __str__(self):
        return f"{self.producer}, z roku {self.production_year}. Pojemność: {self.volume}"

barek/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView

from barek.models import Cabinet, Bottle


# Create your views here.
class CabinetListView(ListView):
    model = Cabinet


class CreateCabinetView(CreateView):
    model = Cabinet
    fields = ['location']


class CabinetDetailView(DetailView):
    model = Cabinet


class CreateBottleView(CreateView):
    model = Bottle
    fields = ['cabinet', 'producer', 'production_year', 'volume']

templates/barek/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Barek</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>

{%  include 'barek/top_menu.html' %}

<div class="container">
    {% block content %}
    {%  endblock %}
</div>

</body>
</html>

templates/barek/bottle_form.html
{% extends 'barek/base.html' %}

{% block content %}

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock %}

templates/barek/cabinet_detail.html
{%  extends 'barek/base.html' %}

{% block content %}

    <h1>{{ cabinet.location }}</h1>

    <div>
    <p>{{ cabinet.bottle_set.all|join:"<br>" }}</p>
    </div>

{% endblock %}

templates/barek/cabinet_form.html
{% extends 'barek/base.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_location" class="form-label">Location:</label>
            <input class="form-control" name="location" cols="40" rows="10" required id="id_location"></input>
        </div>
        <input class="btn btn-primary" type="submit" value="Save">
    </form>

{% endblock %}

templates/barek/cabinet_list.html
{%  extends 'barek/base.html' %}

{% block content %}


    <h2>Cabinets</h2>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>Lokalizacja szafki</th>
                <th>Ilość butelek</th>
                <th>Akcja</th>
            </tr>
        </thead>
        <tbody>
        {% for cabinet in object_list %}
            <tr>
                <td>{{ cabinet.location }}</td>
                <td>100</td>
                <td>EDYTUJ / USUŃ</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>

{%  endblock %}

templates/barek/top_menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>